force-app/main/default/objects/OdooIntegrationSettings__c/OdooIntegrationSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Odoo Integration Settings</label>
</CustomObject>

force-app/main/default/objects/OdooIntegrationSettings__c/fields/IP2_Enabled__c.field-meta.xml
<CustomField>
    <fullName>IP2_Enabled__c</fullName>
    <defaultValue>true</defaultValue>
    <label>IP-2 Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OdooIntegrationSettings__c/fields/IP2_Sync_Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>IP2_Sync_Batch_Size__c</fullName>
    <defaultValue>1</defaultValue>
    <label>IP-2 Sync Batch Size</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AssetSyncSchedulable.cls
/**
 * AssetSyncSchedulable
 * Schedules AssetSyncBatch (IP-2) at 02:00 HKT daily.
 *
 * To activate, run via Anonymous Apex:
 *   String cron = '0 0 18 * * ?'; // 18:00 UTC = 02:00 HKT next day
 *   System.schedule('DE IP-2 Asset Sync Daily', cron, new AssetSyncSchedulable());
 */
global class AssetSyncSchedulable implements Schedulable {
    global void execute(SchedulableContext sc) {
        OdooIntegrationSettings__c s = OdooIntegrationSettings__c.getOrgDefaults();
        if (s.IP2_Enabled__c != true) return;
        Integer batchSize = s.IP2_Sync_Batch_Size__c != null
                            ? Integer.valueOf(s.IP2_Sync_Batch_Size__c) : 1;
        Database.executeBatch(new AssetSyncBatch(), batchSize);
    }
}