force-app/main/default/objects/Account/fields/DE_Entity__c.field-meta.xml
<CustomField>
    <fullName>DE_Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The primary DE subsidiary for this customer Account. Lookup to Account with RecordType = DE_Entity. Auto-populated from the first Quote that triggers Finance Approval.</description>
    <inlineHelpText>The primary DE subsidiary for this customer. Set automatically from the first Quote.</inlineHelpText>
    <label>Primary DE Subsidiary</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Accounts</relationshipLabel>
    <relationshipName>Customer_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Operation_Country__c.field-meta.xml
<CustomField>
    <fullName>Operation_Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Cayman Islands</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>Hong Kong</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Indonesia</fullName>
            </value>
            <value>
                <fullName>Ireland</fullName>
            </value>
            <value>
                <fullName>Italy</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>Lithuania</fullName>
            </value>
            <value>
                <fullName>Luxembourg</fullName>
            </value>
            <value>
                <fullName>Malaysia</fullName>
            </value>
            <value>
                <fullName>Netherlands</fullName>
            </value>
            <value>
                <fullName>Panama</fullName>
            </value>
            <value>
                <fullName>Philippines</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>South Korea</fullName>
            </value>
            <value>
                <fullName>Sri Lanka</fullName>
            </value>
            <value>
                <fullName>Switzerland</fullName>
            </value>
            <value>
                <fullName>Taiwan</fullName>
            </value>
            <value>
                <fullName>Thailand</fullName>
            </value>
            <value>
                <fullName>United Arab Emirates</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>United States</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Tax_ID__c.field-meta.xml
<CustomField>
    <fullName>Tax_ID__c</fullName>
    <description>Tax ID / Business Registration Number. Duplicate check on this field at Account level.</description>
    <inlineHelpText>Tax ID / Business Registration Number. Duplicate check on this field at Account level.</inlineHelpText>
    <label>Tax ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/DE_Entity.recordType-meta.xml
<RecordType>
    <fullName>DE_Entity</fullName>
    <active>true</active>
    <description>Digital Edge legal entities (subsidiaries). Records of this type represent DE contracting companies: DE HK Ltd, DE SG Pte Ltd, DE KR Co Ltd, DE PH Inc, DE ID PT, DE JP KK. Used as the contracting party on Opportunity.DE_Entity__c.</description>
    <label>DE Entity</label>
</RecordType>

force-app/main/default/objects/Asset/fields/BillingAccount__c.field-meta.xml
<CustomField>
    <fullName>BillingAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The BAN (Billing Account Number) this asset is billed under. Set when the order is confirmed and an asset is provisioned. Drives billing reconciliation between SF assets and Odoo subscriptions.</inlineHelpText>
    <label>Billing Account</label>
    <referenceTo>BillingAccount__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BillingAccount__c/BillingAccount__c.object-meta.xml
<CustomObject>
    <label>BAN</label>
    <nameField>
        <label>BAN Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BANs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/BillingAccount__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>BANs</relationshipLabel>
    <relationshipName>Billing_Accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BillingAccount__c/fields/Billing_Contact__c.field-meta.xml
<CustomField>
    <fullName>Billing_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The primary customer contact for billing queries and invoice disputes on this BAN. This person receives invoice delivery notifications if no Invoice Delivery Email is set.</inlineHelpText>
    <label>Billing Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Contact_Status__c</field>
            <operation>notEqual</operation>
            <value>Inactive</value>
        </filterItems>
        <filterItems>
            <field>Contact.Contact_Status__c</field>
            <operation>notEqual</operation>
            <value>Departed</value>
        </filterItems>
        <infoMessage>Only Active contacts are shown. Inactive and Departed contacts are excluded.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipName>BillingAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BillingAccount__c/fields/DE_Entity__c.field-meta.xml
<CustomField>
    <fullName>DE_Entity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The DE subsidiary for this BAN. Defaults from the Account&apos;s Primary Subsidiary or the Quote&apos;s subsidiary. Can be changed during BAN creation.</description>
    <inlineHelpText>The DE subsidiary for this BAN. Determines the default currency and finance routing.</inlineHelpText>
    <label>DE Subsidiary</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>DE Entity</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Subsidiary_BANs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DE_Entity__c.field-meta.xml
<CustomField>
    <fullName>DE_Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Digital Edge legal entity contracting with this customer for this deal. Lookup to an Account record with RecordType = DE Entity. Replaces the Account-level DE_Subsidiary__c picklist so one Account can deal with multiple DE entities across Opportunities.</description>
    <inlineHelpText>Select the Digital Edge legal entity responsible for this deal (e.g. DE JP KK for Japan, DE SG Pte Ltd for Singapore). Set per Opportunity - one customer can have different contracting entities across deals.</inlineHelpText>
    <label>DE Subsidiary</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Contracting Entity)</relationshipLabel>
    <relationshipName>Contracting_Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Operation_Country__c.field-meta.xml
<CustomField>
    <fullName>Operation_Country__c</fullName>
    <description>Primary DE market for this deal. Determines country sales team, pricebook, and BAN currency.</description>
    <inlineHelpText>The Digital Edge country market for this deal. Drives pricebook, billing currency, and routing to the correct country sales team.</inlineHelpText>
    <label>Operation Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>Indonesia</fullName>
            </value>
            <value>
                <fullName>Philippines</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Thailand</fullName>
            </value>
            <value>
                <fullName>Malaysia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Change Order</fullName>
            </value>
            <value>
                <fullName>Termination</fullName>
            </value>
            <value>
                <fullName>Novation</fullName>
            </value>
            <value>
                <fullName>Ramp</fullName>
            </value>
            <value>
                <fullName>Change/Upsell</fullName>
            </value>
            <value>
                <fullName>Churn</fullName>
            </value>
            <value>
                <fullName>Partial Churn</fullName>
            </value>
            <value>
                <fullName>BAN Change</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/BillingAccount__c.field-meta.xml
<CustomField>
    <fullName>BillingAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The BAN that invoices will be raised against for this order. Carried over from the accepted Quote automatically. Verify before activating the order.</inlineHelpText>
    <label>BAN</label>
    <referenceTo>BillingAccount__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Operation_Country__c.field-meta.xml
<CustomField>
    <fullName>Operation_Country__c</fullName>
    <inlineHelpText>Country code for the Digital Edge market where services are delivered. Carried from the Opportunity.</inlineHelpText>
    <label>Operation Country</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <inlineHelpText>The type of commercial action this order executes. Drives the provisioning workflow and asset lifecycle update. Set automatically from the Quote Type on order creation.</inlineHelpText>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Service</fullName>
                <default>true</default>
                <label>New Service</label>
            </value>
            <value>
                <fullName>Change/Upsell</fullName>
            </value>
            <value>
                <fullName>Churn</fullName>
            </value>
            <value>
                <fullName>Partial Churn</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Suspension</fullName>
            </value>
            <value>
                <fullName>Resumption</fullName>
            </value>
            <value>
                <fullName>BAN Change</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Charge_Type__c.field-meta.xml
<CustomField>
    <fullName>Charge_Type__c</fullName>
    <label>Charge Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>MRC</fullName>
                <default>true</default>
                <label>MRC</label>
            </value>
            <value>
                <fullName>NRC</fullName>
            </value>
            <value>
                <fullName>Usage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Charge_Type__c.field-meta.xml
<CustomField>
    <fullName>Charge_Type__c</fullName>
    <label>Charge Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MRC</fullName>
            </value>
            <value>
                <fullName>NRC</fullName>
            </value>
            <value>
                <fullName>Usage-Based</fullName>
            </value>
            <value>
                <fullName>Additional Charge</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AssetActivationServiceTest.cls
/**
 * AssetActivationServiceTest
 *
 * Tests for AssetActivationService covering:
 *   1. New Order → creates Assets from MRC OrderItems
 *   2. CO CHANGE → end-dates old asset, creates replacement
 *   3. CO DELETE → end-dates old asset only
 *   4. BAN Change CO → updates BillingAccount__c on existing assets (AST-004)
 *   5. BAN Change CO with no items → no error
 */
@IsTest
private class AssetActivationServiceTest {

    @TestSetup
    static void setup() {
        Account acc = new Account(
            Name = 'Asset Test Account',
            Operation_Country__c = 'Singapore',
            Tax_ID__c = 'AST12345X'
        );
        insert acc;

        Id deEntityRtId = Schema.SObjectType.Account
            .getRecordTypeInfosByDeveloperName().get('DE_Entity').getRecordTypeId();
        Account sgEntity = new Account(
            Name = 'DE SG Pte Ltd',
            RecordTypeId = deEntityRtId
        );
        insert sgEntity;

        Contact ctc = new Contact(
            FirstName = 'Asset',
            LastName = 'TestContact',
            AccountId = acc.Id,
            Email = 'asset.test@example.com'
        );
        insert ctc;

        BillingAccount__c oldBan = new BillingAccount__c(
            Name = 'OLD-BAN-001',
            Account__c = acc.Id,
            Billing_Contact__c = ctc.Id,
            DE_Entity__c = sgEntity.Id
        );
        insert oldBan;

        BillingAccount__c newBan = new BillingAccount__c(
            Name = 'NEW-BAN-002',
            Account__c = acc.Id,
            Billing_Contact__c = ctc.Id,
            DE_Entity__c = sgEntity.Id
        );
        insert newBan;

        Opportunity opp = new Opportunity(
            Name = 'Asset Test Opp',
            AccountId = acc.Id,
            StageName = '3-Qualified',
            CloseDate = Date.today().addMonths(3)
        );
        insert opp;

        Id stdPbId = Test.getStandardPricebookId();

        Product2 mrcProd = new Product2(
            Name = 'Test MRC Product',
            ProductCode = 'ASTTEST.RC',
            IsActive = true
        );
        insert mrcProd;

        PricebookEntry pbe = new PricebookEntry(
            Pricebook2Id = stdPbId,
            Product2Id = mrcProd.Id,
            UnitPrice = 500.00,
            IsActive = true
        );
        insert pbe;

        // Original New Service Order
        Order origOrder = new Order(
            AccountId = acc.Id,
            OpportunityId = opp.Id,
            EffectiveDate = Date.today(),
            Status = 'Draft',
            Pricebook2Id = stdPbId,
            Order_Type__c = 'New Service',
            BillingAccount__c = oldBan.Id
        );
        insert origOrder;

        OrderItem origItem = new OrderItem(
            OrderId = origOrder.Id,
            Product2Id = mrcProd.Id,
            PricebookEntryId = pbe.Id,
            Quantity = 1,
            UnitPrice = 500.00,
            Charge_Type__c = 'MRC',
            Description = 'Test Cabinet Service'
        );
        insert origItem;
    }

    // ─── Test 1: New Order creates assets ──────────────────────────────────

    @IsTest
    static void testNewOrderCreatesAssets() {
        Order ord = [SELECT Id FROM Order WHERE Order_Type__c = 'New Service' LIMIT 1];

        Test.startTest();
        AssetActivationService.Request req = new AssetActivationService.Request();
        req.orderId = ord.Id;
        AssetActivationService.activateAssets(new List<AssetActivationService.Request>{ req });
        Test.stopTest();

        List<Asset> assets = [
            SELECT Id, Name, Status, Asset_Lifecycle_Status__c, Source_Order__c
            FROM Asset
            WHERE Source_Order__c = :ord.Id
        ];
        System.assertEquals(1, assets.size(), 'One asset should be created for MRC OrderItem');
        System.assertEquals('In Service', assets[0].Asset_Lifecycle_Status__c);
    }

    // ─── Test 2: BAN Change CO updates asset BAN ──────────────────────────

    @IsTest
    static void testBanChangeUpdatesAssetBan() {
        Order origOrder = [SELECT Id, AccountId, OpportunityId, Pricebook2Id
                           FROM Order WHERE Order_Type__c = 'New Service' LIMIT 1];
        OrderItem origItem = [SELECT Id FROM OrderItem WHERE OrderId = :origOrder.Id LIMIT 1];
        BillingAccount__c oldBan = [SELECT Id FROM BillingAccount__c WHERE Name = 'OLD-BAN-001' LIMIT 1];
        BillingAccount__c newBan = [SELECT Id FROM BillingAccount__c WHERE Name = 'NEW-BAN-002' LIMIT 1];

        // First, create the asset via New Order activation
        AssetActivationService.Request req1 = new AssetActivationService.Request();
        req1.orderId = origOrder.Id;
        AssetActivationService.activateAssets(new List<AssetActivationService.Request>{ req1 });

        // Set BAN on the asset
        Asset a = [SELECT Id FROM Asset WHERE Source_Order__c = :origOrder.Id LIMIT 1];
        a.BillingAccount__c = oldBan.Id;
        update a;

        // Create BAN Change CO
        Order banCO = new Order(
            AccountId = origOrder.AccountId,
            OpportunityId = origOrder.OpportunityId,
            EffectiveDate = Date.today(),
            Status = 'Draft',
            Pricebook2Id = origOrder.Pricebook2Id,
            Order_Type__c = 'BAN Change',
            BillingAccount__c = newBan.Id,
            Original_Order__c = origOrder.Id
        );
        insert banCO;

        // CO item referencing original order item
        PricebookEntry pbe = [SELECT Id, Product2Id FROM PricebookEntry LIMIT 1];
        OrderItem coItem = new OrderItem(
            OrderId = banCO.Id,
            Product2Id = pbe.Product2Id,
            PricebookEntryId = pbe.Id,
            Quantity = 1,
            UnitPrice = 500.00,
            Charge_Type__c = 'MRC',
            ns_change_type__c = 'NO_CHANGE',
            Original_OrderItem__c = origItem.Id
        );
        insert coItem;

        Test.startTest();
        AssetActivationService.Request req2 = new AssetActivationService.Request();
        req2.orderId = banCO.Id;
        AssetActivationService.activateAssets(new List<AssetActivationService.Request>{ req2 });
        Test.stopTest();

        Asset updated = [SELECT Id, BillingAccount__c FROM Asset WHERE Id = :a.Id];
        System.assertEquals(newBan.Id, updated.BillingAccount__c,
            'Asset BillingAccount should be updated to the new BAN from the CO');
    }

    // ─── Test 3: BAN Change with no CO items is safe ──────────────────────

    @IsTest
    static void testBanChangeNoItemsNoError() {
        Order origOrder = [SELECT Id, AccountId, OpportunityId, Pricebook2Id
                           FROM Order WHERE Order_Type__c = 'New Service' LIMIT 1];
        BillingAccount__c newBan = [SELECT Id FROM BillingAccount__c WHERE Name = 'NEW-BAN-002' LIMIT 1];

        Order banCO = new Order(
            AccountId = origOrder.AccountId,
            OpportunityId = origOrder.OpportunityId,
            EffectiveDate = Date.today(),
            Status = 'Draft',
            Pricebook2Id = origOrder.Pricebook2Id,
            Order_Type__c = 'BAN Change',
            BillingAccount__c = newBan.Id,
            Original_Order__c = origOrder.Id
        );
        insert banCO;

        Test.startTest();
        AssetActivationService.Request req = new AssetActivationService.Request();
        req.orderId = banCO.Id;
        AssetActivationService.activateAssets(new List<AssetActivationService.Request>{ req });
        Test.stopTest();

        System.assert(true, 'BAN Change with no CO items should not throw');
    }

    // ─── Test 4: CO CHANGE creates replacement asset ──────────────────────

    @IsTest
    static void testChangeOrderCreatesReplacement() {
        Order origOrder = [SELECT Id, AccountId, OpportunityId, Pricebook2Id
                           FROM Order WHERE Order_Type__c = 'New Service' LIMIT 1];
        OrderItem origItem = [SELECT Id FROM OrderItem WHERE OrderId = :origOrder.Id LIMIT 1];

        // Activate original order first
        AssetActivationService.Request req1 = new AssetActivationService.Request();
        req1.orderId = origOrder.Id;
        AssetActivationService.activateAssets(new List<AssetActivationService.Request>{ req1 });

        // Create CO with CHANGE item
        Order changeCO = new Order(
            AccountId = origOrder.AccountId,
            OpportunityId = origOrder.OpportunityId,
            EffectiveDate = Date.today(),
            Status = 'Draft',
            Pricebook2Id = origOrder.Pricebook2Id,
            Order_Type__c = 'Change/Upsell',
            Original_Order__c = origOrder.Id
        );
        insert changeCO;

        PricebookEntry pbe = [SELECT Id, Product2Id FROM PricebookEntry LIMIT 1];
        OrderItem coItem = new OrderItem(
            OrderId = changeCO.Id,
            Product2Id = pbe.Product2Id,
            PricebookEntryId = pbe.Id,
            Quantity = 2,
            UnitPrice = 700.00,
            Charge_Type__c = 'MRC',
            ns_change_type__c = 'CHANGE',
            Original_OrderItem__c = origItem.Id,
            Description = 'Upgraded Cabinet Service'
        );
        insert coItem;

        Test.startTest();
        AssetActivationService.Request req2 = new AssetActivationService.Request();
        req2.orderId = changeCO.Id;
        AssetActivationService.activateAssets(new List<AssetActivationService.Request>{ req2 });
        Test.stopTest();

        // Original asset should be terminated
        Asset origAsset = [
            SELECT Id, Status, Asset_Lifecycle_Status__c
            FROM Asset WHERE Source_Order__c = :origOrder.Id LIMIT 1
        ];
        System.assertEquals('Terminated', origAsset.Asset_Lifecycle_Status__c,
            'Original asset should be terminated on CO activation');

        // New replacement asset should be created
        List<Asset> newAssets = [
            SELECT Id, Status, Asset_Lifecycle_Status__c, Source_Order__c
            FROM Asset WHERE Source_Order__c = :changeCO.Id
        ];
        System.assertEquals(1, newAssets.size(), 'Replacement asset should be created');
        System.assertEquals('In Service', newAssets[0].Asset_Lifecycle_Status__c);
    }
}