force-app/main/default/objects/Account/fields/DE_Entity__c.field-meta.xml
<CustomField>
    <fullName>DE_Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The primary DE subsidiary for this customer Account. Lookup to Account with RecordType = DE_Entity. Auto-populated from the first Quote that triggers Finance Approval.</description>
    <inlineHelpText>The primary DE subsidiary for this customer. Set automatically from the first Quote.</inlineHelpText>
    <label>Primary DE Subsidiary</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Accounts</relationshipLabel>
    <relationshipName>Customer_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Operation_Country__c.field-meta.xml
<CustomField>
    <fullName>Operation_Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Cayman Islands</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>Hong Kong</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Indonesia</fullName>
            </value>
            <value>
                <fullName>Ireland</fullName>
            </value>
            <value>
                <fullName>Italy</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>Lithuania</fullName>
            </value>
            <value>
                <fullName>Luxembourg</fullName>
            </value>
            <value>
                <fullName>Malaysia</fullName>
            </value>
            <value>
                <fullName>Netherlands</fullName>
            </value>
            <value>
                <fullName>Panama</fullName>
            </value>
            <value>
                <fullName>Philippines</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>South Korea</fullName>
            </value>
            <value>
                <fullName>Sri Lanka</fullName>
            </value>
            <value>
                <fullName>Switzerland</fullName>
            </value>
            <value>
                <fullName>Taiwan</fullName>
            </value>
            <value>
                <fullName>Thailand</fullName>
            </value>
            <value>
                <fullName>United Arab Emirates</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>United States</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Tax_ID__c.field-meta.xml
<CustomField>
    <fullName>Tax_ID__c</fullName>
    <description>Tax ID / Business Registration Number. Duplicate check on this field at Account level.</description>
    <inlineHelpText>Tax ID / Business Registration Number. Duplicate check on this field at Account level.</inlineHelpText>
    <label>Tax ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/DE_Entity.recordType-meta.xml
<RecordType>
    <fullName>DE_Entity</fullName>
    <active>true</active>
    <description>Digital Edge legal entities (subsidiaries). Records of this type represent DE contracting companies: DE HK Ltd, DE SG Pte Ltd, DE KR Co Ltd, DE PH Inc, DE ID PT, DE JP KK. Used as the contracting party on Opportunity.DE_Entity__c.</description>
    <label>DE Entity</label>
</RecordType>

force-app/main/default/objects/BillingAccount__c/BillingAccount__c.object-meta.xml
<CustomObject>
    <label>BAN</label>
    <nameField>
        <label>BAN Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BANs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/BillingAccount__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>BANs</relationshipLabel>
    <relationshipName>Billing_Accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BillingAccount__c/fields/BAN_Number__c.field-meta.xml
<CustomField>
    <fullName>BAN_Number__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Auto-generated billing account identifier with country prefix. This is the BANID used in BOSS for sales order line tagging and invoicing.</inlineHelpText>
    <label>BAN ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/BillingAccount__c/fields/DE_Entity__c.field-meta.xml
<CustomField>
    <fullName>DE_Entity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The DE subsidiary for this BAN. Defaults from the Account&apos;s Primary Subsidiary or the Quote&apos;s subsidiary. Can be changed during BAN creation.</description>
    <inlineHelpText>The DE subsidiary for this BAN. Determines the default currency and finance routing.</inlineHelpText>
    <label>DE Subsidiary</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>DE Entity</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Subsidiary_BANs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BillingAccountTriggerHandlerTest.cls
@IsTest
private class BillingAccountTriggerHandlerTest {

    @TestSetup
    static void setup() {
        Account acc = new Account(
            Name = 'BAN Handler Test Co',
            Operation_Country__c = 'Singapore',
            Tax_ID__c = 'T12345678X'
        );
        insert acc;

        Id rtId = Schema.SObjectType.Account
            .getRecordTypeInfosByDeveloperName().get('DE_Entity').getRecordTypeId();
        Account sgEntity = new Account(
            Name = 'DE SG Pte Ltd',
            RecordTypeId = rtId
        );
        insert sgEntity;
    }

    @IsTest
    static void testBeforeInsert_generatesBanNumber() {
        Account acc = [SELECT Id FROM Account WHERE Name = 'BAN Handler Test Co' LIMIT 1];
        Account sgEntity = [SELECT Id FROM Account WHERE Name = 'DE SG Pte Ltd' LIMIT 1];

        BillingAccount__c ban = new BillingAccount__c(
            Account__c   = acc.Id,
            DE_Entity__c = sgEntity.Id
        );

        Test.startTest();
        insert ban;
        Test.stopTest();

        BillingAccount__c inserted = [SELECT BAN_Number__c, Name FROM BillingAccount__c WHERE Id = :ban.Id];
        System.assertNotEquals(null, inserted, 'BAN record should be inserted');
    }

    @IsTest
    static void testBeforeInsert_skipExistingBanNumber() {
        Account acc = [SELECT Id FROM Account WHERE Name = 'BAN Handler Test Co' LIMIT 1];
        Account sgEntity = [SELECT Id FROM Account WHERE Name = 'DE SG Pte Ltd' LIMIT 1];

        BillingAccount__c ban = new BillingAccount__c(
            Account__c    = acc.Id,
            BAN_Number__c = 'SG99001',
            Name          = 'SG99001',
            DE_Entity__c  = sgEntity.Id
        );

        Test.startTest();
        insert ban;
        Test.stopTest();

        BillingAccount__c inserted = [SELECT BAN_Number__c FROM BillingAccount__c WHERE Id = :ban.Id];
        System.assertEquals('SG99001', inserted.BAN_Number__c,
            'Pre-populated BAN number should be preserved');
    }
}