force-app/main/default/objects/Account/fields/Operation_Country__c.field-meta.xml
<CustomField>
    <fullName>Operation_Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Cayman Islands</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>Hong Kong</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Indonesia</fullName>
            </value>
            <value>
                <fullName>Ireland</fullName>
            </value>
            <value>
                <fullName>Italy</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>Lithuania</fullName>
            </value>
            <value>
                <fullName>Luxembourg</fullName>
            </value>
            <value>
                <fullName>Malaysia</fullName>
            </value>
            <value>
                <fullName>Netherlands</fullName>
            </value>
            <value>
                <fullName>Panama</fullName>
            </value>
            <value>
                <fullName>Philippines</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>South Korea</fullName>
            </value>
            <value>
                <fullName>Sri Lanka</fullName>
            </value>
            <value>
                <fullName>Switzerland</fullName>
            </value>
            <value>
                <fullName>Taiwan</fullName>
            </value>
            <value>
                <fullName>Thailand</fullName>
            </value>
            <value>
                <fullName>United Arab Emirates</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>United States</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>Direct end-customers of Digital Edge. Standard billing and contracting flow. This is the primary record type.</description>
    <label>1 - Customer</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/DE_Entity.recordType-meta.xml
<RecordType>
    <fullName>DE_Entity</fullName>
    <active>true</active>
    <description>Digital Edge legal entities (subsidiaries). Records of this type represent DE contracting companies: DE HK Ltd, DE SG Pte Ltd, DE KR Co Ltd, DE PH Inc, DE ID PT, DE JP KK. Used as the contracting party on Opportunity.DE_Entity__c.</description>
    <label>DE Entity</label>
</RecordType>

force-app/main/default/objects/Asset/fields/MRC__c.field-meta.xml
<CustomField>
    <fullName>MRC__c</fullName>
    <inlineHelpText>The monthly billing amount for this asset in USD. Populated from the Order line item at provisioning. Passed to Odoo for subscription billing. Do not edit manually.</inlineHelpText>
    <label>Monthly Recurring Charge (USD)</label>
    <precision>15</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Asset/fields/NRC__c.field-meta.xml
<CustomField>
    <fullName>NRC__c</fullName>
    <inlineHelpText>One-time charge for this asset such as installation or fit-out fees. Populated from the Order line item at provisioning. Invoiced once, not part of recurring billing.</inlineHelpText>
    <label>Non-Recurring Charge (USD)</label>
    <precision>15</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Odoo_IB_ID__c.field-meta.xml
<CustomField>
    <fullName>Odoo_IB_ID__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Populated automatically by the Odoo integration. Do not edit manually.</inlineHelpText>
    <label>Odoo Install Base ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Asset/fields/Odoo_Subscription_ID__c.field-meta.xml
<CustomField>
    <fullName>Odoo_Subscription_ID__c</fullName>
    <inlineHelpText>Populated automatically by the Odoo integration. Do not edit manually.</inlineHelpText>
    <label>Odoo Subscription ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Operation_Site__c.field-meta.xml
<CustomField>
    <fullName>Operation_Site__c</fullName>
    <inlineHelpText>The Digital Edge data centre site where this asset is physically located. Populated from the Order at provisioning.</inlineHelpText>
    <label>Site</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HK01</fullName>
            </value>
            <value>
                <fullName>HK02</fullName>
            </value>
            <value>
                <fullName>SG01</fullName>
            </value>
            <value>
                <fullName>KR01</fullName>
            </value>
            <value>
                <fullName>PH01</fullName>
            </value>
            <value>
                <fullName>ID01</fullName>
            </value>
            <value>
                <fullName>JP01</fullName>
            </value>
            <value>
                <fullName>BKK1</fullName>
                <isActive>false</isActive>
                <label>BKK1</label>
            </value>
            <value>
                <fullName>BKK2</fullName>
                <isActive>false</isActive>
                <label>BKK2</label>
            </value>
            <value>
                <fullName>BOM1</fullName>
                <isActive>false</isActive>
                <label>BOM1</label>
            </value>
            <value>
                <fullName>BOM2</fullName>
                <isActive>false</isActive>
                <label>BOM2</label>
            </value>
            <value>
                <fullName>BOM3</fullName>
                <isActive>false</isActive>
                <label>BOM3</label>
            </value>
            <value>
                <fullName>CGK1</fullName>
                <isActive>false</isActive>
                <label>CGK1</label>
            </value>
            <value>
                <fullName>CGK2</fullName>
                <isActive>false</isActive>
                <label>CGK2</label>
            </value>
            <value>
                <fullName>CGK7</fullName>
                <isActive>false</isActive>
                <label>CGK7</label>
            </value>
            <value>
                <fullName>JKT1</fullName>
                <isActive>false</isActive>
                <label>JKT1</label>
            </value>
            <value>
                <fullName>JKT2</fullName>
                <isActive>false</isActive>
                <label>JKT2</label>
            </value>
            <value>
                <fullName>MNL1</fullName>
                <isActive>false</isActive>
                <label>MNL1</label>
            </value>
            <value>
                <fullName>OSA1</fullName>
                <isActive>false</isActive>
                <label>OSA1</label>
            </value>
            <value>
                <fullName>OSA2</fullName>
                <isActive>false</isActive>
                <label>OSA2</label>
            </value>
            <value>
                <fullName>PEK1</fullName>
                <isActive>false</isActive>
                <label>PEK1</label>
            </value>
            <value>
                <fullName>PUS1</fullName>
                <isActive>false</isActive>
                <label>PUS1</label>
            </value>
            <value>
                <fullName>SEL1</fullName>
                <isActive>false</isActive>
                <label>SEL1</label>
            </value>
            <value>
                <fullName>SEL2</fullName>
                <isActive>false</isActive>
                <label>SEL2</label>
            </value>
            <value>
                <fullName>TYO1</fullName>
                <isActive>false</isActive>
                <label>TYO1</label>
            </value>
            <value>
                <fullName>TYO2</fullName>
                <isActive>false</isActive>
                <label>TYO2</label>
            </value>
            <value>
                <fullName>TYO3</fullName>
                <isActive>false</isActive>
                <label>TYO3</label>
            </value>
            <value>
                <fullName>TYO4</fullName>
                <isActive>false</isActive>
                <label>TYO4</label>
            </value>
            <value>
                <fullName>TYO5</fullName>
                <isActive>false</isActive>
                <label>TYO5</label>
            </value>
            <value>
                <fullName>TYO6</fullName>
                <isActive>false</isActive>
                <label>TYO6</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Odoo_Subscription_ID__c.field-meta.xml
<CustomField>
    <fullName>Odoo_Subscription_ID__c</fullName>
    <inlineHelpText>Odoo subscription record ID. Set by IP-2 (OdooOrderConfirmHandler). Used to link change orders (IP-4) to the original subscription.</inlineHelpText>
    <label>Odoo Subscription ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Operation_Country__c.field-meta.xml
<CustomField>
    <fullName>Operation_Country__c</fullName>
    <inlineHelpText>Country code for the Digital Edge market where services are delivered. Carried from the Opportunity.</inlineHelpText>
    <label>Operation Country</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Operation_Site__c.field-meta.xml
<CustomField>
    <fullName>Operation_Site__c</fullName>
    <inlineHelpText>The Digital Edge data centre where services under this order are delivered. Carried from the Quote. Used for provisioning routing and asset assignment.</inlineHelpText>
    <label>Site</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>TYO1</fullName>
            </value>
            <value>
                <fullName>TYO2</fullName>
            </value>
            <value>
                <fullName>TYO3</fullName>
            </value>
            <value>
                <fullName>TYO4</fullName>
            </value>
            <value>
                <fullName>TYO5</fullName>
            </value>
            <value>
                <fullName>TYO6</fullName>
            </value>
            <value>
                <fullName>TYO7</fullName>
            </value>
            <value>
                <fullName>OSA1</fullName>
            </value>
            <value>
                <fullName>OSA2</fullName>
            </value>
            <value>
                <fullName>SEL1</fullName>
            </value>
            <value>
                <fullName>SEL2</fullName>
            </value>
            <value>
                <fullName>SEL3</fullName>
            </value>
            <value>
                <fullName>PUS1</fullName>
            </value>
            <value>
                <fullName>JKT1</fullName>
            </value>
            <value>
                <fullName>JKT2</fullName>
            </value>
            <value>
                <fullName>CGK1</fullName>
            </value>
            <value>
                <fullName>MNL1</fullName>
            </value>
            <value>
                <fullName>PEK1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <inlineHelpText>The type of commercial action this order executes. Drives the provisioning workflow and asset lifecycle update. Set automatically from the Quote Type on order creation.</inlineHelpText>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Service</fullName>
                <default>true</default>
                <label>New Service</label>
            </value>
            <value>
                <fullName>Change/Upsell</fullName>
            </value>
            <value>
                <fullName>Churn</fullName>
            </value>
            <value>
                <fullName>Partial Churn</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Suspension</fullName>
            </value>
            <value>
                <fullName>Resumption</fullName>
            </value>
            <value>
                <fullName>BAN Change</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Charge_Type__c.field-meta.xml
<CustomField>
    <fullName>Charge_Type__c</fullName>
    <label>Charge Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>MRC</fullName>
                <default>true</default>
                <label>MRC</label>
            </value>
            <value>
                <fullName>NRC</fullName>
            </value>
            <value>
                <fullName>Usage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Paired_MRC_OrderItem__c.field-meta.xml
<CustomField>
    <fullName>Paired_MRC_OrderItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Paired MRC OrderItem</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipName>NRC_OrderItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Charge_Type__c.field-meta.xml
<CustomField>
    <fullName>Charge_Type__c</fullName>
    <label>Charge Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MRC</fullName>
            </value>
            <value>
                <fullName>NRC</fullName>
            </value>
            <value>
                <fullName>Usage-Based</fullName>
            </value>
            <value>
                <fullName>Additional Charge</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OdooAssetStatusHandlerTest.cls
/**
 * OdooAssetStatusHandlerTest
 * Tests for IP-2 inbound endpoint — subscription + lines array structure.
 * Event types: new_service, amendment, churn, renewal, suspension, resumption.
 */
@IsTest
private class OdooAssetStatusHandlerTest {

    // ─── Test data setup ──────────────────────────────────────────────────────────

    @TestSetup
    static void setup() {
        Account acc = new Account(
            Name                 = 'IP2 Test Account',
            BillingCountry       = 'Singapore',
            Operation_Country__c = 'Singapore',
            RecordTypeId         = [
                SELECT Id FROM RecordType
                WHERE SObjectType = 'Account' AND DeveloperName = 'Customer' LIMIT 1
            ].Id
        );
        insert acc;

        Id deEntityRtId = Schema.SObjectType.Account
            .getRecordTypeInfosByDeveloperName().get('DE_Entity').getRecordTypeId();
        Account sgEntity = new Account(
            Name = 'DE SG Pte Ltd',
            RecordTypeId = deEntityRtId
        );
        insert sgEntity;

        Product2 mrcProd = new Product2(
            Name        = 'Test Cabinet MRC',
            ProductCode = 'TESTIP2.RC',
            IsActive    = true
        );
        insert mrcProd;

        Product2 nrcProd = new Product2(
            Name        = 'Test Cabinet NRC',
            ProductCode = 'TESTIP2.NR',
            IsActive    = true
        );
        insert nrcProd;

        Id stdPbId = Test.getStandardPricebookId();
        insert new List<PricebookEntry>{
            new PricebookEntry(Pricebook2Id = stdPbId, Product2Id = mrcProd.Id,
                               UnitPrice = 1000.00, IsActive = true),
            new PricebookEntry(Pricebook2Id = stdPbId, Product2Id = nrcProd.Id,
                               UnitPrice = 1650.00, IsActive = true)
        };

        Order ord = new Order(
            AccountId         = acc.Id,
            Status            = 'Draft',
            EffectiveDate     = Date.today(),
            Operation_Site__c = 'JKT1',
            Pricebook2Id      = stdPbId,
            Order_Type__c     = 'New Service'
        );
        insert ord;

        PricebookEntry mrcPbe = [
            SELECT Id FROM PricebookEntry
            WHERE Pricebook2Id = :stdPbId AND Product2Id = :mrcProd.Id LIMIT 1
        ];
        OrderItem mrcItem = new OrderItem(
            OrderId          = ord.Id,
            PricebookEntryId = mrcPbe.Id,
            Quantity         = 2,
            UnitPrice        = 1000.00,
            Charge_Type__c   = 'MRC',
            Description      = 'Test Cabinet'
        );
        insert mrcItem;

        PricebookEntry nrcPbe = [
            SELECT Id FROM PricebookEntry
            WHERE Pricebook2Id = :stdPbId AND Product2Id = :nrcProd.Id LIMIT 1
        ];
        insert new OrderItem(
            OrderId                 = ord.Id,
            PricebookEntryId        = nrcPbe.Id,
            Quantity                = 2,
            UnitPrice               = 1650.00,
            Charge_Type__c          = 'NRC',
            Paired_MRC_OrderItem__c = mrcItem.Id,
            Description             = 'Test Cabinet NRC'
        );
    }

    // ─── HTTP routing ─────────────────────────────────────────────────────────────

    @IsTest
    static void testUnknownEventType_Returns400() {
        Map<String, Object> payload = new Map<String, Object>{
            'event_type'  => 'unknown_type',
            'odoo_sub_id' => 999,
            'lines'       => new List<Object>{
                new Map<String, Object>{ 'odoo_ib_id' => 999 }
            }
        };
        RestContext.request  = buildRequest(payload);
        RestContext.response = new RestResponse();

        Test.startTest();
        OdooAssetStatusHandler.handlePost();
        Test.stopTest();

        System.assertEquals(400, RestContext.response.statusCode,
            'Unknown event_type should return 400');
    }

    @IsTest
    static void testMissingLines_Returns400() {
        Map<String, Object> payload = new Map<String, Object>{
            'event_type'  => 'amendment',
            'odoo_sub_id' => 2001
            // lines omitted
        };
        RestContext.request  = buildRequest(payload);
        RestContext.response = new RestResponse();

        Test.startTest();
        OdooAssetStatusHandler.handlePost();
        Test.stopTest();

        System.assertEquals(400, RestContext.response.statusCode,
            'Missing lines array should return 400');
    }

    @IsTest
    static void testNewService_MissingSfOrderId_Returns422() {
        OrderItem mrcItem = [SELECT Id FROM OrderItem WHERE Charge_Type__c = 'MRC' LIMIT 1];

        Map<String, Object> payload = new Map<String, Object>{
            'event_type'  => 'new_service',
            'odoo_sub_id' => 2001,
            // sf_order_id omitted
            'lines'       => new List<Object>{
                new Map<String, Object>{
                    'odoo_ib_id'      => 1001,
                    'sf_orderitem_id' => String.valueOf(mrcItem.Id),
                    'mrr'             => 2000.00,
                    'quantity'        => 1
                }
            }
        };
        RestContext.request  = buildRequest(payload);
        RestContext.response = new RestResponse();

        Test.startTest();
        OdooAssetStatusHandler.handlePost();
        Test.stopTest();

        System.assertEquals(422, RestContext.response.statusCode,
            'new_service without sf_order_id should return 422');
    }

    // ─── new_service ──────────────────────────────────────────────────────────────

    @IsTest
    static void testNewService_CreatesAssetAndWritesSubLineId() {
        Order ord         = [SELECT Id FROM Order LIMIT 1];
        OrderItem mrcItem = [SELECT Id FROM OrderItem WHERE Charge_Type__c = 'MRC' LIMIT 1];

        OdooAssetStatusHandler.LineItem line = new OdooAssetStatusHandler.LineItem();
        line.odoo_ib_id      = 1001L;
        line.id              = 3001L;
        line.sf_orderitem_id = mrcItem.Id;
        line.mrr             = 2000.00;
        line.quantity        = 2;
        line.start_date      = String.valueOf(Date.today());
        line.ns_product_attribute_value = 'false'; // handler dereferences this field unconditionally

        OdooAssetStatusHandler.AssetEventPayload p = new OdooAssetStatusHandler.AssetEventPayload();
        p.event_type  = 'new_service';
        p.odoo_sub_id = 2001L;
        p.sf_order_id = ord.Id;
        p.lines       = new List<OdooAssetStatusHandler.LineItem>{ line };

        Test.startTest();
        List<Id> result = OdooAssetStatusHandler.handleNewService(p);
        Test.stopTest();

        System.assertEquals(1, result.size(), 'One Asset should be created');

        List<Asset> assets = [
            SELECT Id, MRC__c, NRC__c, Odoo_IB_ID__c, Odoo_Subscription_ID__c,
                   Asset_Lifecycle_Status__c, Source_OrderItem__c
            FROM Asset
            WHERE Source_OrderItem__c = :mrcItem.Id
        ];
        System.assertEquals(1,            assets.size(),                          'One Asset record expected');
        System.assertEquals(2000.00,      assets[0].MRC__c,                       'MRC should match mrr payload');
        System.assertEquals(3300.00,      assets[0].NRC__c,                       'NRC = 2 qty × 1650 unit price');
        System.assertEquals('1001',       assets[0].Odoo_IB_ID__c,                'Odoo IB ID should be stored');
        System.assertEquals('2001',       assets[0].Odoo_Subscription_ID__c,      'Odoo Sub ID should be stored');
        System.assertEquals('In Service', assets[0].Asset_Lifecycle_Status__c,    'Lifecycle status should be In Service');

        OrderItem updatedOi = [SELECT Odoo_Sub_Line_ID__c FROM OrderItem WHERE Id = :mrcItem.Id];
        System.assertEquals('3001', updatedOi.Odoo_Sub_Line_ID__c,
            'Sub line ID should be written back to OrderItem for IP-4 change orders');
    }

    @IsTest
    static void testNewService_MultiLine_CreatesTwoAssets() {
        Order ord         = [SELECT Id FROM Order LIMIT 1];
        OrderItem mrcItem = [SELECT Id FROM OrderItem WHERE Charge_Type__c = 'MRC' LIMIT 1];

        // Second product + OrderItem (no paired NRC — NRC will default to 0)
        Id stdPbId = Test.getStandardPricebookId();
        Product2 prod2 = new Product2(Name = 'Test Cabinet 2', IsActive = true);
        insert prod2;
        PricebookEntry pbe2 = new PricebookEntry(
            Pricebook2Id = stdPbId, Product2Id = prod2.Id,
            UnitPrice = 500.00, IsActive = true);
        insert pbe2;
        OrderItem mrcItem2 = new OrderItem(
            OrderId          = ord.Id,
            PricebookEntryId = pbe2.Id,
            Quantity         = 1,
            UnitPrice        = 500.00,
            Charge_Type__c   = 'MRC',
            Description      = 'Test Cabinet 2'
        );
        insert mrcItem2;

        OdooAssetStatusHandler.LineItem line1 = new OdooAssetStatusHandler.LineItem();
        line1.odoo_ib_id     = 1101L;
        line1.id             = 3101L;
        line1.sf_orderitem_id = mrcItem.Id;
        line1.mrr            = 2000.00;
        line1.quantity       = 2;
        line1.start_date     = String.valueOf(Date.today());
        line1.ns_product_attribute_value = 'false';

        OdooAssetStatusHandler.LineItem line2 = new OdooAssetStatusHandler.LineItem();
        line2.odoo_ib_id     = 1102L;
        line2.id             = 3102L;
        line2.sf_orderitem_id = mrcItem2.Id;
        line2.mrr            = 500.00;
        line2.quantity       = 1;
        line2.start_date     = String.valueOf(Date.today());
        line2.ns_product_attribute_value = 'false';

        OdooAssetStatusHandler.AssetEventPayload p = new OdooAssetStatusHandler.AssetEventPayload();
        p.event_type  = 'new_service';
        p.odoo_sub_id = 2101L;
        p.sf_order_id = ord.Id;
        p.lines       = new List<OdooAssetStatusHandler.LineItem>{ line1, line2 };

        Test.startTest();
        List<Id> result = OdooAssetStatusHandler.handleNewService(p);
        Test.stopTest();

        System.assertEquals(2, result.size(), 'Two Assets should be created for two lines');
        System.assertEquals(2,
            [SELECT COUNT() FROM Asset WHERE Odoo_Subscription_ID__c = '2101'],
            'Both Assets should carry the correct subscription ID');
    }

    @IsTest
    static void testNewService_ViaRestEndpoint_Returns200() {
        Order ord         = [SELECT Id FROM Order LIMIT 1];
        OrderItem mrcItem = [SELECT Id FROM OrderItem WHERE Charge_Type__c = 'MRC' LIMIT 1];

        Map<String, Object> payload = new Map<String, Object>{
            'event_type'  => 'new_service',
            'odoo_sub_id' => 2002,
            'sf_order_id' => String.valueOf(ord.Id),
            'lines'       => new List<Object>{
                new Map<String, Object>{
                    'odoo_ib_id'      => 1002,
                    'id'              => 3002,
                    'sf_orderitem_id' => String.valueOf(mrcItem.Id),
                    'mrr'             => 2000.00,
                    'quantity'         => 2,
                    'start_date'       => String.valueOf(Date.today()),
                    'ns_product_attribute_value' => 'false'
                }
            }
        };
        RestContext.request  = buildRequest(payload);
        RestContext.response = new RestResponse();

        Test.startTest();
        OdooAssetStatusHandler.handlePost();
        Test.stopTest();

        System.assertEquals(200, RestContext.response.statusCode,
            'Valid new_service payload should return 200');
        String body = RestContext.response.responseBody.toString();
        System.assert(body.contains('"processed":1'),    'Response body should report processed=1');
        System.assert(body.contains('"asset_ids"'),      'Response body should include asset_ids array');
    }

    @IsTest
    static void testNewService_MergeIbTask_SingleAssetWithQuantity() {
        Order ord = [SELECT Id FROM Order LIMIT 1];

        // Product with Merge_IB_Task__c = TRUE → one Asset carrying the full quantity
        Product2 mergeProd = new Product2(Name = 'Merge Cabinet', IsActive = true, Merge_IB_Task__c = true);
        insert mergeProd;
        PricebookEntry pbe = new PricebookEntry(Pricebook2Id = Test.getStandardPricebookId(),
            Product2Id = mergeProd.Id, UnitPrice = 900.00, IsActive = true);
        insert pbe;
        OrderItem mergeItem = new OrderItem(OrderId = ord.Id, PricebookEntryId = pbe.Id,
            Quantity = 5, UnitPrice = 900.00, Charge_Type__c = 'MRC', Description = 'Merge Cabinet');
        insert mergeItem;

        OdooAssetStatusHandler.LineItem line = new OdooAssetStatusHandler.LineItem();
        line.id                = 4001L;
        line.sf_orderitem_id   = mergeItem.Id;
        line.subscription_id   = 4100L;
        line.project_task_ids  = new List<Long>{ 8001L, 8002L, 8003L };
        line.mrr               = 900.00;
        line.quantity          = 5;
        line.start_date        = String.valueOf(Date.today());
        line.ns_product_attribute_value = 'false';

        OdooAssetStatusHandler.AssetEventPayload p = new OdooAssetStatusHandler.AssetEventPayload();
        p.event_type  = 'new_service';
        p.sf_order_id = ord.Id;
        p.lines       = new List<OdooAssetStatusHandler.LineItem>{ line };

        Test.startTest();
        List<Id> result = OdooAssetStatusHandler.handleNewService(p);
        Test.stopTest();

        System.assertEquals(1, result.size(), 'Merge mode should create exactly ONE Asset');
        Asset a = [SELECT Quantity, Odoo_IB_ID__c FROM Asset WHERE Source_OrderItem__c = :mergeItem.Id LIMIT 1];
        System.assertEquals(5, a.Quantity, 'Merged Asset should carry the full Odoo quantity');
        System.assertEquals('8001,8002,8003', a.Odoo_IB_ID__c, 'All task IDs should be combined on the single Asset');
    }

    // ─── amendment ───────────────────────────────────────────────────────────────

    @IsTest
    static void testAmendment_UpdatesAssetMrc() {
        Account acc = [SELECT Id FROM Account LIMIT 1];
        Asset a = new Asset(
            Name                      = 'Amendment Test Asset',
            AccountId                 = acc.Id,
            Status                    = 'Installed',
            Asset_Lifecycle_Status__c = 'In Service',
            MRC__c                    = 1000.00,
            Quantity                  = 1,
            Odoo_IB_ID__c             = '5001',
            InstallDate               = Date.today()
        );
        insert a;

        OdooAssetStatusHandler.LineItem line = new OdooAssetStatusHandler.LineItem();
        line.odoo_ib_id  = 5001L;
        line.mrr         = 1500.00;
        line.quantity    = 2;
        line.ns_product_attribute_value = 'false';

        OdooAssetStatusHandler.AssetEventPayload p = new OdooAssetStatusHandler.AssetEventPayload();
        p.event_type  = 'amendment';
        p.odoo_sub_id = 2003L;
        p.lines       = new List<OdooAssetStatusHandler.LineItem>{ line };

        Test.startTest();
        List<Id> result = OdooAssetStatusHandler.handleAmendment(p);
        Test.stopTest();

        System.assertEquals(1, result.size(), 'One Asset should be updated');
        Asset updated = [SELECT MRC__c, Quantity FROM Asset WHERE Id = :a.Id];
        System.assertEquals(1500.00, updated.MRC__c,   'MRC should be updated to 1500');
        System.assertEquals(2,       updated.Quantity,  'Quantity should be updated to 2');
    }

    @IsTest
    static void testAmendment_AssetNotFound_Returns200WithZeroProcessed() {
        // Unmatched lines are logged to DE_Integration_Error__c — endpoint does not reject
        Map<String, Object> payload = new Map<String, Object>{
            'event_type'  => 'amendment',
            'odoo_sub_id' => 2004,
            'lines'       => new List<Object>{
                new Map<String, Object>{
                    'odoo_ib_id'  => 99999,
                    'mrr'         => 999.00
                }
            }
        };
        RestContext.request  = buildRequest(payload);
        RestContext.response = new RestResponse();

        Test.startTest();
        OdooAssetStatusHandler.handlePost();
        Test.stopTest();

        System.assertEquals(200, RestContext.response.statusCode,
            'Unmatched lines are logged, not rejected — endpoint returns 200');
        System.assert(
            RestContext.response.responseBody.toString().contains('"processed":0'),
            'Processed count should be 0 when no matching Assets exist');
    }

    // ─── churn ────────────────────────────────────────────────────────────────────

    @IsTest
    static void testChurn_TerminatesAsset() {
        Account acc = [SELECT Id FROM Account LIMIT 1];
        Asset a = new Asset(
            Name                      = 'Churn Test Asset',
            AccountId                 = acc.Id,
            Status                    = 'Installed',
            Asset_Lifecycle_Status__c = 'In Service',
            MRC__c                    = 800.00,
            Quantity                  = 1,
            Odoo_IB_ID__c             = '6001',
            InstallDate               = Date.today()
        );
        insert a;

        OdooAssetStatusHandler.LineItem line = new OdooAssetStatusHandler.LineItem();
        line.odoo_ib_id = 6001L;
        line.termination_date = String.valueOf(Date.today());

        OdooAssetStatusHandler.AssetEventPayload p = new OdooAssetStatusHandler.AssetEventPayload();
        p.event_type = 'churn';
        p.lines      = new List<OdooAssetStatusHandler.LineItem>{ line };

        Test.startTest();
        List<Id> result = OdooAssetStatusHandler.handleChurn(p);
        Test.stopTest();

        System.assertEquals(1, result.size(), 'One Asset should be churned');
        Asset churned = [
            SELECT Asset_Lifecycle_Status__c, Status, Termination_Date__c
            FROM Asset WHERE Id = :a.Id
        ];
        System.assertEquals('Terminated', churned.Asset_Lifecycle_Status__c,
            'Asset lifecycle status should be Terminated');
        System.assertEquals('Closed',     churned.Status,
            'churn sets Asset Status to Closed');
        System.assertEquals(Date.today(), churned.Termination_Date__c,
            'Termination date should match payload');
    }

    // ─── renewal ─────────────────────────────────────────────────────────────────

    @IsTest
    static void testRenewal_UpdatesAsset() {
        Account acc = [SELECT Id FROM Account LIMIT 1];
        Asset a = new Asset(
            Name                      = 'Renewal Test Asset',
            AccountId                 = acc.Id,
            Status                    = 'Installed',
            Asset_Lifecycle_Status__c = 'In Service',
            MRC__c                    = 700.00,
            Quantity                  = 1,
            Odoo_IB_ID__c             = '7001',
            InstallDate               = Date.today()
        );
        insert a;

        OdooAssetStatusHandler.LineItem line = new OdooAssetStatusHandler.LineItem();
        line.odoo_ib_id  = 7001L;
        line.mrr         = 750.00;
        line.start_date  = String.valueOf(Date.today().addYears(1));

        OdooAssetStatusHandler.AssetEventPayload p = new OdooAssetStatusHandler.AssetEventPayload();
        p.event_type  = 'renewal';
        p.odoo_sub_id = 9001L;
        p.lines       = new List<OdooAssetStatusHandler.LineItem>{ line };

        Test.startTest();
        List<Id> result = OdooAssetStatusHandler.handleRenewal(p);
        Test.stopTest();

        System.assertEquals(1, result.size(), 'One Asset should be renewed');
        Asset renewed = [
            SELECT MRC__c, Asset_Lifecycle_Status__c, Odoo_Subscription_ID__c
            FROM Asset WHERE Id = :a.Id
        ];
        System.assertEquals(750.00,       renewed.MRC__c,                   'MRC should be updated on renewal');
        System.assertEquals('In Service', renewed.Asset_Lifecycle_Status__c, 'Lifecycle should remain In Service');
        System.assertEquals('9001',       renewed.Odoo_Subscription_ID__c,  'Sub ID should be updated');
    }

    // ─── suspension ──────────────────────────────────────────────────────────────

    @IsTest
    static void testSuspension_SuspendsAsset() {
        Account acc = [SELECT Id FROM Account LIMIT 1];
        Asset a = new Asset(
            Name                      = 'Suspension Test Asset',
            AccountId                 = acc.Id,
            Status                    = 'Installed',
            Asset_Lifecycle_Status__c = 'In Service',
            MRC__c                    = 900.00,
            Quantity                  = 1,
            Odoo_IB_ID__c             = '8001',
            InstallDate               = Date.today()
        );
        insert a;

        OdooAssetStatusHandler.LineItem line = new OdooAssetStatusHandler.LineItem();
        line.odoo_ib_id = 8001L;

        OdooAssetStatusHandler.AssetEventPayload p = new OdooAssetStatusHandler.AssetEventPayload();
        p.event_type = 'suspension';
        p.lines      = new List<OdooAssetStatusHandler.LineItem>{ line };

        Test.startTest();
        List<Id> result = OdooAssetStatusHandler.handleSuspension(p);
        Test.stopTest();

        System.assertEquals(1, result.size(), 'One Asset should be suspended');
        Asset suspended = [SELECT Asset_Lifecycle_Status__c, Status FROM Asset WHERE Id = :a.Id];
        System.assertEquals('Suspended', suspended.Asset_Lifecycle_Status__c,
            'Asset lifecycle status should be Suspended');
        System.assertEquals('Installed', suspended.Status,
            'Asset status should remain Installed — physically still present');
    }

    @IsTest
    static void testSuspension_ViaRestEndpoint_Returns200() {
        Account acc = [SELECT Id FROM Account LIMIT 1];
        insert new Asset(
            Name                      = 'Suspension REST Asset',
            AccountId                 = acc.Id,
            Status                    = 'Installed',
            Asset_Lifecycle_Status__c = 'In Service',
            MRC__c                    = 100.00,
            Quantity                  = 1,
            Odoo_IB_ID__c             = '8002',
            InstallDate               = Date.today()
        );

        Map<String, Object> payload = new Map<String, Object>{
            'event_type'  => 'suspension',
            'odoo_sub_id' => 2005,
            'lines'       => new List<Object>{
                new Map<String, Object>{ 'odoo_ib_id' => 8002 }
            }
        };
        RestContext.request  = buildRequest(payload);
        RestContext.response = new RestResponse();

        Test.startTest();
        OdooAssetStatusHandler.handlePost();
        Test.stopTest();

        System.assertEquals(200, RestContext.response.statusCode,
            'Valid suspension payload should return 200');
    }

    // ─── resumption ──────────────────────────────────────────────────────────────

    @IsTest
    static void testResumption_RestoresAsset() {
        Account acc = [SELECT Id FROM Account LIMIT 1];
        Asset a = new Asset(
            Name                      = 'Resumption Test Asset',
            AccountId                 = acc.Id,
            Status                    = 'Installed',
            Asset_Lifecycle_Status__c = 'Suspended',
            MRC__c                    = 900.00,
            Quantity                  = 1,
            Odoo_IB_ID__c             = '9001',
            InstallDate               = Date.today()
        );
        insert a;

        OdooAssetStatusHandler.LineItem line = new OdooAssetStatusHandler.LineItem();
        line.odoo_ib_id = 9001L;

        OdooAssetStatusHandler.AssetEventPayload p = new OdooAssetStatusHandler.AssetEventPayload();
        p.event_type = 'resumption';
        p.lines      = new List<OdooAssetStatusHandler.LineItem>{ line };

        Test.startTest();
        List<Id> result = OdooAssetStatusHandler.handleResumption(p);
        Test.stopTest();

        System.assertEquals(1, result.size(), 'One Asset should be resumed');
        Asset resumed = [SELECT Asset_Lifecycle_Status__c FROM Asset WHERE Id = :a.Id];
        System.assertEquals('In Service', resumed.Asset_Lifecycle_Status__c,
            'Asset lifecycle status should be restored to In Service');
    }

    @IsTest
    static void testResumption_AssetNotFound_Returns200WithZeroProcessed() {
        Map<String, Object> payload = new Map<String, Object>{
            'event_type'  => 'resumption',
            'odoo_sub_id' => 2006,
            'lines'       => new List<Object>{
                new Map<String, Object>{ 'odoo_ib_id' => 99998 }
            }
        };
        RestContext.request  = buildRequest(payload);
        RestContext.response = new RestResponse();

        Test.startTest();
        OdooAssetStatusHandler.handlePost();
        Test.stopTest();

        System.assertEquals(200, RestContext.response.statusCode,
            'Unmatched lines are logged, not rejected — endpoint returns 200');
        System.assert(
            RestContext.response.responseBody.toString().contains('"processed":0'),
            'Processed count should be 0 when no matching Assets exist');
    }

    // ─── Helpers ─────────────────────────────────────────────────────────────────

    private static RestRequest buildRequest(Map<String, Object> payload) {
        RestRequest req = new RestRequest();
        req.requestBody = Blob.valueOf(JSON.serialize(payload));
        req.httpMethod  = 'POST';
        return req;
    }
}